In [1]:
# Jovian Commit Essentials
# Please retain and execute this cell without modifying the contents for `jovian.commit` to work
!pip install jovian --upgrade -q
import jovian
jovian.set_project('course-project')
jovian.set_colab_id('18IxyirU-UyV4site6NrQLG0uXOZgfJV0')

c:\Users\itspr\AppData\Local\Programs\Python\Python312\Lib\site-packages\jovian\utils\latest.py:4: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import parse_version

# course-project

Use the "Run" button to execute the code.

In [2]:
!pip install jovian --upgrade --quiet

In [3]:
import jovian

In [4]:
# Execute this to save new versions of the notebook
jovian.commit(project="course-project")

[jovian] Error: Failed to read the Jupyter notebook. Please re-run this cell to try again. If the issue persists, provide the "filename" argument to "jovian.commit" e.g. "jovian.commit(filename='my-notebook.ipynb')"

In [5]:
!pip install opendatasets --upgrade --quiet

In [6]:
import pandas as pd
import numpy as np
import opendatasets as od

In [7]:
dataset_url = 'https://www.kaggle.com/c/GiveMeSomeCredit/'

In [ ]:
od.download(dataset_url)

Please provide your Kaggle credentials to download this dataset. Learn more: http://bit.ly/kaggle-creds
Your Kaggle username:

In [ ]:
!pip install scikit-learn --upgrade --quiet

In [ ]:
import os

In [ ]:
data_dir = './GiveMeSomeCredit'

In [ ]:
os.listdir(data_dir)

['Data Dictionary.xls', 'cs-training.csv', 'cs-test.csv', 'sampleEntry.csv']

In [ ]:
train_csv = data_dir + '/cs-training.csv'
test_csv = data_dir + '/cs-test.csv'

In [ ]:
train_df = pd.read_csv(train_csv)

In [ ]:
train_df

        Unnamed: 0  ...  NumberOfDependents
0                1  ...                 2.0
1                2  ...                 1.0
2                3  ...                 0.0
3                4  ...                 0.0
4                5  ...                 0.0
...            ...  ...                 ...
149995      149996  ...                 0.0
149996      149997  ...                 2.0
149997      149998  ...                 0.0
149998      149999  ...                 0.0
149999      150000  ...                 0.0

[150000 rows x 12 columns]

In [ ]:
test_df = pd.read_csv(test_csv)

In [ ]:
test_df

        Unnamed: 0  ...  NumberOfDependents
0                1  ...                 0.0
1                2  ...                 2.0
2                3  ...                 2.0
3                4  ...                 0.0
4                5  ...                 1.0
...            ...  ...                 ...
101498      101499  ...                 0.0
101499      101500  ...                 4.0
101500      101501  ...                 NaN
101501      101502  ...                 3.0
101502      101503  ...                 0.0

[101503 rows x 12 columns]

In [ ]:
jovian.commit()

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
Committed successfully! https://jovian.ai/sarathchandrikaksc/course-project

'https://jovian.ai/sarathchandrikaksc/course-project'

In [ ]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 12 columns):
 #   Column                                Non-Null Count   Dtype
---  ------                                --------------   -----
 0   Unnamed: 0                            150000 non-null  int64
 1   SeriousDlqin2yrs                      150000 non-null  int64
 2   RevolvingUtilizationOfUnsecuredLines  150000 non-null  float64
 3   age                                   150000 non-null  int64
 4   NumberOfTime30-59DaysPastDueNotWorse  150000 non-null  int64
 5   DebtRatio                             150000 non-null  float64
 6   MonthlyIncome                         120269 non-null  float64
 7   NumberOfOpenCreditLinesAndLoans       150000 non-null  int64
 8   NumberOfTimes90DaysLate               150000 non-null  int64
 9   NumberRealEstateLoansOrLines          150000 non-null  int64
 10  NumberOfTime60-89DaysPastDueNotWorse  150000 non-null  int64
 11  NumberOfDependents                    146076 non-null  float64
dtypes: float64(4), int64(8)
memory usage: 13.7 MB

In [ ]:
type(train_df)

pandas.core.frame.DataFrame

In [ ]:
train_df.drop(train_df.columns[0], axis=1, inplace=True)

In [ ]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 11 columns):
 #   Column                                Non-Null Count   Dtype
---  ------                                --------------   -----
 0   SeriousDlqin2yrs                      150000 non-null  int64
 1   RevolvingUtilizationOfUnsecuredLines  150000 non-null  float64
 2   age                                   150000 non-null  int64
 3   NumberOfTime30-59DaysPastDueNotWorse  150000 non-null  int64
 4   DebtRatio                             150000 non-null  float64
 5   MonthlyIncome                         120269 non-null  float64
 6   NumberOfOpenCreditLinesAndLoans       150000 non-null  int64
 7   NumberOfTimes90DaysLate               150000 non-null  int64
 8   NumberRealEstateLoansOrLines          150000 non-null  int64
 9   NumberOfTime60-89DaysPastDueNotWorse  150000 non-null  int64
 10  NumberOfDependents                    146076 non-null  float64
dtypes: float64(4), int64(7)
memory usage: 12.6 MB

In [ ]:
train_df.describe()

       SeriousDlqin2yrs  ...  NumberOfDependents
count     150000.000000  ...       146076.000000
mean           0.066840  ...            0.757222
std            0.249746  ...            1.115086
min            0.000000  ...            0.000000
25%            0.000000  ...            0.000000
50%            0.000000  ...            0.000000
75%            0.000000  ...            1.000000
max            1.000000  ...           20.000000

[8 rows x 11 columns]

In [ ]:
train_df.head(10)

   SeriousDlqin2yrs  ...  NumberOfDependents
0                 1  ...                 2.0
1                 0  ...                 1.0
2                 0  ...                 0.0
3                 0  ...                 0.0
4                 0  ...                 0.0
5                 0  ...                 1.0
6                 0  ...                 0.0
7                 0  ...                 0.0
8                 0  ...                 NaN
9                 0  ...                 2.0

[10 rows x 11 columns]

**Dataset and Problem Statement Description:**

Kaggle Challenege: Give Me Some Credit (https://www.kaggle.com/c/GiveMeSomeCredit/overview)

Dataset: Contains of 150000 rows and 11 columns.

Problem Statement: Predicting the probability that somebody will experience financial distress in two years. 

Target Column: SeriousDlqin2yrs

In [ ]:
train_df.isna().sum()

SeriousDlqin2yrs                            0
RevolvingUtilizationOfUnsecuredLines        0
age                                         0
NumberOfTime30-59DaysPastDueNotWorse        0
DebtRatio                                   0
MonthlyIncome                           29731
NumberOfOpenCreditLinesAndLoans             0
NumberOfTimes90DaysLate                     0
NumberRealEstateLoansOrLines                0
NumberOfTime60-89DaysPastDueNotWorse        0
NumberOfDependents                       3924
dtype: int64

There are around 25k+ null values for MonthlyIncome and 4k values for number of Dependents. 

Since out of 150000 30000 are null, replacing null with mean of the income or median of the income whichever is less. 

Null values of Number of dependents can be updated either by taking count of number of unique values in the column and using the least count or taking nearest integer to the average of all number of dependents whichever is less.

In [ ]:
train_df['MonthlyIncome'].mean()

6670.221237392844

In [ ]:
train_df['MonthlyIncome'].median()

5400.0

In [ ]:
train_df['MonthlyIncome'].corr(train_df['SeriousDlqin2yrs'])

-0.01974554677105983

In [ ]:
train_df.fillna(value=train_df['MonthlyIncome'])

(0.0, 3008750.0)